### ISSUE TITLE
mysql_real_escape_string_quote issue when building with mariadb-devel

### ISSUE THREAD

**Issue by scop** [PyMySQL/mysqlclient-python#114]
When compiling current git master against mariadb-devel 10.0.26 on Fedora 23 x86_64, build succeeds but use fails:

```
ImportError: ./_mysql.so: undefined symbol: mysql_real_escape_string_quote
```

I suppose more elaborate checks than just `MYSQL_VERSION_ID >= 50707` are needed to handle this case.

```
$ cat /usr/include/mysql/mysql_version.h 
/* Copyright Abandoned 1996,1999 TCX DataKonsult AB & Monty Program KB
   & Detron HB, 1996, 1999-2004, 2007 MySQL AB.
   This file is public domain and comes with NO WARRANTY of any kind
*/

/* Version numbers for protocol & mysqld */

#ifndef _mysql_version_h
#define _mysql_version_h
#ifdef _CUSTOMCONFIG_
#include <custom_conf.h>
#else
#define PROTOCOL_VERSION		10
#define MYSQL_SERVER_VERSION		"10.0.26-MariaDB"
#define MYSQL_BASE_VERSION		"mysqld-10.0"
#define MARIADB_BASE_VERSION		"mariadb-10.0"
#define MYSQL_SERVER_SUFFIX_DEF		""
#define FRM_VER				6
#define MYSQL_VERSION_ID		100026
#define MYSQL_PORT			3306
#define MYSQL_PORT_DEFAULT		0
#define MYSQL_UNIX_ADDR			"/var/lib/mysql/mysql.sock"
#define MYSQL_CONFIG_NAME		"my"
#define MYSQL_COMPILATION_COMMENT	"MariaDB Server"

/* mysqld compile time options */
#endif /* _CUSTOMCONFIG_ */

#ifndef LICENSE
#define LICENSE				GPL
#endif /* LICENSE */

#endif /* _mysql_version_h */
```

**Comment by hobbes1069** [comment]
I'm still running into this issue on Fedora Rawhide (future f28 release) with mysqlclient-python 1.3.10 which seems to have the referenced pull request applied...
```
$ python
Python 2.7.13 (default, Jun 26 2017, 10:16:32) 
[GCC 7.1.1 20170526 (Red Hat 7.1.1-2)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import MySQLdb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/MySQLdb/__init__.py", line 19, in <module>
    import _mysql
ImportError: /usr/lib64/python2.7/site-packages/_mysql.so: undefined symbol: mysql_real_escape_string_quote
```

**Comment by methane** [comment]
I don't use Fedora and MariaDB.  I'm very busy.  I won't consume my time and energy for such annoying issue.
Please consult with Fedora and MariaDB.
