### ISSUE TITLE
When install mysqlclient, got a message 'Command "python setup.py egg_info" failed with error code 1' on Mac OSX.

### ISSUE THREAD

**Issue by iandmyhand** [PyMySQL/mysqlclient-python#180]
I'm trying to install the 'mysqlclient', but it failed with below message.
```
pip install mysqlclient --no-cache-dir
Collecting mysqlclient
  Downloading mysqlclient-1.3.10.tar.gz (82kB)
    100% |████████████████████████████████| 92kB 351kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/6t/xvmz_v4s3b76t1jb7vqpl8_r0000gn/T/pip-build-g8emf9wa/mysqlclient/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "/private/var/folders/6t/xvmz_v4s3b76t1jb7vqpl8_r0000gn/T/pip-build-g8emf9wa/mysqlclient/setup_posix.py", line 54, in get_config
        libraries = [dequote(i[2:]) for i in libs if i.startswith('-l')]
      File "/private/var/folders/6t/xvmz_v4s3b76t1jb7vqpl8_r0000gn/T/pip-build-g8emf9wa/mysqlclient/setup_posix.py", line 54, in <listcomp>
        libraries = [dequote(i[2:]) for i in libs if i.startswith('-l')]
      File "/private/var/folders/6t/xvmz_v4s3b76t1jb7vqpl8_r0000gn/T/pip-build-g8emf9wa/mysqlclient/setup_posix.py", line 12, in dequote
        if s[0] in "\"'" and s[0] == s[-1]:
    IndexError: string index out of range

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/6t/xvmz_v4s3b76t1jb7vqpl8_r0000gn/T/pip-build-g8emf9wa/mysqlclient/
```

I already install the 'mysql-connector-c' with a command ```brew install mysql-connector-c```, and I don't know how to solve this problem.

My environments are these:
- Mac OS version: macOS Sierra 10.12.5
- Python version: Python 3.6.0 GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)

**Comment by methane** [comment]
You should search recent issues before filing one.
