### ISSUE TITLE
mysql_real_escape_string_quote error again on MariaDB 10.2.8

### ISSUE THREAD

**Issue by friscoMad** [PyMySQL/mysqlclient-python#199]
After your last fix I tried to clone and install the lastest dev to get it working and got this error but dismissed it as I thought I had done something wrong.

```
root@host [~/.cache/pip]# pip install git+https://github.com/PyMySQL/mysqlclient-python.git --ignore-installed
Collecting git+https://github.com/PyMySQL/mysqlclient-python.git
  Cloning https://github.com/PyMySQL/mysqlclient-python.git to /tmp/pip-4FZlMu-build
Installing collected packages: mysqlclient
  Running setup.py install for mysqlclient ... done
Successfully installed mysqlclient-1.3.11rc1
root@host [~/.cache/pip]# python
Python 2.7.5 (default, Nov  6 2016, 00:28:07)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import MySQLdb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/MySQLdb/__init__.py", line 19, in <module>
    import _mysql
ImportError: /usr/lib64/python2.7/site-packages/_mysql.so: undefined symbol: mysql_real_escape_string_quote
```

I was reminded that pip support installing from git and tested again with the same error.
I have found that you fixed it at #114 but for some reason it seems that MARIADB_BASE_VERSION is not anymore in mariadb_version.h:
```

root@host [~/.cache/pip]# cat /usr/include/mysql/mariadb_version.h
/* Copyright Abandoned 1996, 1999, 2001 MySQL AB
   This file is public domain and comes with NO WARRANTY of any kind */

/* Version numbers for protocol & mysqld */

#ifndef _mariadb_version_h_
#define _mariadb_version_h_

#ifdef _CUSTOMCONFIG_
#include <custom_conf.h>
#else
#define PROTOCOL_VERSION                10
#define MARIADB_CLIENT_VERSION_STR      "10.2.8"
#define MARIADB_VERSION_ID              100208
#define MYSQL_VERSION_ID                100208
#define MARIADB_PORT                    3306
#define MARIADB_UNIX_ADDR               "/var/lib/mysql/mysql.sock"
#define MYSQL_CONFIG_NAME               "my"

#define MARIADB_PACKAGE_VERSION "3.0.2"
#define MARIADB_SYSTEM_TYPE "Linux"
#define MARIADB_MACHINE_TYPE "x86_64"
#define MARIADB_PLUGINDIR "/usr/lib64/mysql/plugin"

/* mysqld compile time options */
#ifndef MYSQL_CHARSET
#define MYSQL_CHARSET                   ""
#endif
#endif

#endif /* _mariadb_version_h_ */
```

**Comment by methane** [comment]
I'm not MariaDB user.
Any suggestion for fix this?

**Comment by friscoMad** [comment]
I did compare 10.1 and 10.2 headers and the only option I can see is
checking both MARIADB_VERSION_ID and MARIADB_BASE_VERSION.
I will do some tests on 10.2 to check there is no other issue and report
back.

2017-08-30 15:55 GMT+02:00 INADA Naoki <notifications@github.com>:

**Comment by friscoMad** [comment]
Tested and at least with that it does not error at import time and I did not see any other reference to mariadb so I think that should be enough.

**Comment by s0m01cp** [comment]
@friscoMad @methane I am facing this issue with MariaDB 10.3.
