### ISSUE TITLE
auth_gssapi_client.so cannot be loaded

### ISSUE THREAD

**Issue by sscherfke** [PyMySQL/mysqlclient-python#209]
mysqlclient cannot load the plugin `auth_gssapi_client.so` even though the files exists:

```
Traceback (most recent call last):
  File "/localhome/stefan/emsconda/envs/acs/lib/python3.6/site-packages/django/db/backends/base/base.py", line 199, inensure_connection
    self.connect()
  File "/localhome/stefan/emsconda/envs/acs/lib/python3.6/site-packages/django/db/backends/base/base.py", line 171, inconnect
    self.connection = self.get_new_connection(conn_params)
  File "/localhome/stefan/emsconda/envs/acs/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 264, in get_new_connection
    conn = Database.connect(**conn_params)
  File "/localhome/stefan/emsconda/envs/acs/lib/python3.6/site-packages/MySQLdb/__init__.py", line 86, in Connect
    return Connection(*args, **kwargs)
  File "/localhome/stefan/emsconda/envs/acs/lib/python3.6/site-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (2059, 'Plugin auth_gssapi_client could not be loaded: lib/plugin/auth_gssapi_client.so: cannot open shared object file: No such file or directory')
```

Maybe resolving the relative path is broken since the plugin definitively exists in `lib/plugin/`.

**Comment by sscherfke** [comment]
I installed the mariadb-connector-c with conda using the following build script:
```bash
mkdir build
cd build

cmake \
    -DCMAKE_INSTALL_PREFIX=$PREFIX \
    -DINSTALL_LIBDIR=lib \
    -DINSTALL_PLUGINDIR=lib/plugin \
    -DCMAKE_BUILD_TYPE=Release \
    ..

make
make install
```
and mysqlclient via
```
MYSQL_CONFIG="$PREFIX/bin/mariadb_config"
$MYSQL_CONFIG --libs
echo "mysql_config = $MYSQL_CONFIG" >> site.cfg
$PYTHON -m pip install -I --no-deps .
```

**Comment by methane** [comment]
I don't use MariaDB, conda, and gssapi.  I don't have any motivation about this.
If you investigate it by yourself and create pull request, I'll review.
But don't hope I'll fix it.

**Comment by methane** [comment]
I recommend you to ask in somewhere before filing issue here,
because it's most likely your setup problem.  This project is just a binding.

MySQL Connector or MariaDB Connector/C loads plugin.  This project is
just a wrapper of them and doesn't implement loading plugin.

If you have some evidence about this is issue of this project, please file an issue again.
