### ISSUE TITLE
Two cases of "UnicodeDecodeError" errors

### ISSUE THREAD

**Issue by Ernest0x** [PyMySQL/mysqlclient-python#21]
I am using mysqlclient-python 1.3.5 with django and I am getting the following errors.

The interesting part of the traceback for the first error is:

    Traceback (most recent call last):
      ...
      File "/path/to/myproject/myapp/admin.py", line 44, in export_action
        for obj in queryset:
      File "/path/to/virtualenv/lib/python3.4/site-packages/django/db/models/query.py", line 141, in __iter__
        self._fetch_all()
      File "/path/to/virtualenv/lib/python3.4/site-packages/django/db/models/query.py", line 966, in _fetch_all
        self._result_cache = list(self.iterator())
      File "/path/to/virtualenv/lib/python3.4/site-packages/django/db/models/query.py", line 265, in iterator
        for row in compiler.results_iter():
      File "/path/to/virtualenv/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 700, in results_iter
        for rows in self.execute_sql(MULTI):
      File "/path/to/virtualenv/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
        cursor.execute(sql, params)
      File "/path/to/virtualenv/lib/python3.4/site-packages/django/db/backends/utils.py", line 65, in execute
        return self.cursor.execute(sql, params)
      File "/path/to/virtualenv/lib/python3.4/site-packages/django/db/backends/mysql/base.py", line 129, in execute
        return self.cursor.execute(query, args)
      File "/path/to/virtualenv/lib/python3.4/site-packages/MySQLdb/cursors.py", line 219, in execute
        self.errorhandler(self, exc, value)
      File "/path/to/virtualenv/lib/python3.4/site-packages/MySQLdb/connections.py", line 38, in defaulterrorhandler
        raise errorvalue
      File "/path/to/virtualenv/lib/python3.4/site-packages/MySQLdb/cursors.py", line 205, in execute
        r = self._query(query)
      File "/path/to/virtualenv/lib/python3.4/site-packages/MySQLdb/cursors.py", line 373, in _query
        self._post_get_result()
      File "/path/to/virtualenv/lib/python3.4/site-packages/MySQLdb/cursors.py", line 377, in _post_get_result
        self._rows = self._fetch_row(0)
      File "/path/to/virtualenv/lib/python3.4/site-packages/MySQLdb/cursors.py", line 345, in _fetch_row
        return self._result.fetch_row(size, self._fetch_type)
      File "/path/to/virtualenv/lib/python3.4/site-packages/MySQLdb/connections.py", line 233, in string_decoder
        return s.decode(string_decoder.charset)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 44: unexpected end of data

I was also getting a similar error with version 1.3.4, which I thought that was solved after upgrading to 1.3.5 (the error stopped after upgrading). But now (one day after the upgrade, without any change) the same error hits again. The intersting part of the traceback for that error is:

    Traceback (most recent call last):
      ...
      File "/path/to/virtualenv/lib/python3.4/site-packages/django/db/models/query.py", line 122, in __len__
        self._fetch_all()
      File "/path/to/virtualenv/lib/python3.4/site-packages/django/db/models/query.py", line 966, in _fetch_all
        self._result_cache = list(self.iterator())
      File "/path/to/virtualenv/lib/python3.4/site-packages/django/db/models/query.py", line 265, in iterator
        for row in compiler.results_iter():
      File "/path/to/virtualenv/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 700, in results_iter
        for rows in self.execute_sql(MULTI):
      File "/path/to/virtualenv/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
        cursor.execute(sql, params)
      File "/path/to/virtualenv/lib/python3.4/site-packages/django/db/backends/utils.py", line 65, in execute
        return self.cursor.execute(sql, params)
      File "/path/to/virtualenv/lib/python3.4/site-packages/django/db/backends/mysql/base.py", line 129, in execute
        return self.cursor.execute(query, args)
      File "/path/to/virtualenv/lib/python3.4/site-packages/MySQLdb/cursors.py", line 219, in execute
        self.errorhandler(self, exc, value)
      File "/path/to/virtualenv/lib/python3.4/site-packages/MySQLdb/connections.py", line 38, in defaulterrorhandler
        raise errorvalue
      File "/path/to/virtualenv/lib/python3.4/site-packages/MySQLdb/cursors.py", line 205, in execute
        r = self._query(query)
      File "/path/to/virtualenv/lib/python3.4/site-packages/MySQLdb/cursors.py", line 373, in _query
        self._post_get_result()
      File "/path/to/virtualenv/lib/python3.4/site-packages/MySQLdb/cursors.py", line 377, in _post_get_result
        self._rows = self._fetch_row(0)
      File "/path/to/virtualenv/lib/python3.4/site-packages/MySQLdb/cursors.py", line 345, in _fetch_row
        return self._result.fetch_row(size, self._fetch_type)
      File "/path/to/virtualenv/lib/python3.4/site-packages/MySQLdb/connections.py", line 233, in string_decoder
        return s.decode(string_decoder.charset)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 1: invalid continuation byte

Any hint?

**Comment by methane** [comment]
Could you show me output of `SHOW CREATE TABLE <tablename>`?
I suppose your table has string (TEXT, VARCHAR, etc...) column with non utf-8 encoding.

**Comment by Ernest0x** [comment]
I have not seen that kind of errors for a while. I think that the problem stopped after restarting the web and wsgi servers.

Info about the database: It is a legacy one, and has latin1 data in tables that have default charset = utf8 (latin1 data encoded as utf-8). To get correct results I have to run "SET NAMES 'latin1';" at connection time. The table columns inherit the character set of the table (there is no character set explicitly set for table columns).

**Comment by methane** [comment]
I may know some about the bug.  But I don't want making this library complex to support such legacy setup....
I recommend you to use latin1 as connection encoding, or `use_unicode=False` option.

**Comment by Ernest0x** [comment]
I added another view (actually a django admin view to a django admin site) that produces the error in the first traceback above:

    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 149: unexpected end of data. 

A difference with other views is that this view takes longer to complete, as it does a join with a relatively big table. What is worth, the error does not happen with development data, but it does occur on production. So, I guess it has to do with either the size of the data returned by the database or the actual data stored in the production database.

Also I am not sure what exactly you meant by recommending me using 'use_unicode=False', but simply adding it as a database option in django settings did not help either, as it caused the following error:

     TypeError: __str__ returned non-string (type bytes)

**Comment by Ernest0x** [comment]
Well, a colleague of mine had an interesting idea for what might be wrong and I tend to agree with him. It could be that 0xce is the first byte of a unicode character and some fields have data truncated to that byte because the initial data in the insert did not fit entirely to the column.

**Comment by methane** [comment]
I think it's too special case.  I don't think Django support such case.
You should migrate your legacy, mis-configured database, or use low-level API.
