### ISSUE TITLE
It's too difficult to install

### ISSUE THREAD

**Issue by rymuscle** [PyMySQL/mysqlclient-python#216]
pip install mysqlclient==1.3.12 

Collecting mysqlclient==1.3.12
  Using cached mysqlclient-1.3.12.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/3t/rpn5rw_51bb1sbyv9qr4x6wr0000gn/T/pip-build-bwj96xl0/mysqlclient/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "/private/var/folders/3t/rpn5rw_51bb1sbyv9qr4x6wr0000gn/T/pip-build-bwj96xl0/mysqlclient/setup_posix.py", line 54, in get_config
        libraries = [dequote(i[2:]) for i in libs if i.startswith('-l')]
      File "/private/var/folders/3t/rpn5rw_51bb1sbyv9qr4x6wr0000gn/T/pip-build-bwj96xl0/mysqlclient/setup_posix.py", line 54, in <listcomp>
        libraries = [dequote(i[2:]) for i in libs if i.startswith('-l')]
      File "/private/var/folders/3t/rpn5rw_51bb1sbyv9qr4x6wr0000gn/T/pip-build-bwj96xl0/mysqlclient/setup_posix.py", line 12, in dequote
        if s[0] in "\"'" and s[0] == s[-1]:
    IndexError: string index out of range
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/3t/rpn5rw_51bb1sbyv9qr4x6wr0000gn/T/pip-build-bwj96xl0/mysqlclient/

**Comment by methane** [comment]
It's very FAQ and bug is in MySQL Connector/C.
Issue tracker is not support forum.  Asking such question means sending spam mail to maintainer.
DON'T ASK QUESTION ON ISSUE TRACKER.

**Comment by pyk** [comment]
@rymuscle hi, you should edit the `mysql_config` as mentioned in the [README.md](https://github.com/PyMySQL/mysqlclient-python#note-about-bug-of-mysql-connectorc-on-macos).

To lookup where the `mysql_config` file on your system, you can use: 

```
which mysql_config
```

then edit it using your text editor.
