### ISSUE TITLE
Can't substitute in table name

### ISSUE THREAD

**Issue by alexjurkiewicz** [PyMySQL/mysqlclient-python#260]
Example code:

```python
conn = MySQLdb.connect(...)
c = conn.cursor()
c.execute("SELECT * from %s LIMIT %s", ("order_events", "1"))
c.fetchall()
```

Causes an error like:

```qml
Traceback (most recent call last):
File "/var/task/handler.py", line 50, in hello
c.execute("SELECT * from %s LIMIT %s", ("order_events", "1"))
File "/var/task/MySQLdb/cursors.py", line 250, in execute
self.errorhandler(self, exc, value)
File "/var/task/MySQLdb/connections.py", line 50, in defaulterrorhandler
raise errorvalue
File "/var/task/MySQLdb/cursors.py", line 247, in execute
res = self._query(query)
File "/var/task/MySQLdb/cursors.py", line 412, in _query
rowcount = self._do_query(q)
File "/var/task/MySQLdb/cursors.py", line 375, in _do_query
db.query(q)
File "/var/task/MySQLdb/connections.py", line 276, in query
_mysql.connection.query(self, query)
_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''order_events' LIMIT '1'' at line 1")

```

I believe this error is because MySQL doesn't accept single quotes `'` around table name. It only accepts backticks `.

```
mysql> select 1 from order_events LIMIT 1;
+---+
| 1 |
+---+
| 1 |
+---+
1 row in set (0.00 sec)

mysql> select 1 from "order_events" LIMIT 1;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"order_events" LIMIT 1' at line 1
mysql> select 1 from 'order_events' LIMIT 1;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''order_events' LIMIT 1' at line 1
mysql> select 1 from `order_events` LIMIT 1;
+---+
| 1 |
+---+
| 1 |
+---+
1 row in set (0.00 sec)
```

**Comment by methane** [comment]
It's expected behavior, not a bug.

**Comment by jeffmjack** [comment]
@methane Why is this considered a feature and not a bug, and what is the correct syntax for table name substitution?
