### ISSUE TITLE
In Python 3, ConfigParser has been renamed to configparser 

### ISSUE THREAD

**Issue by aaronlelevier** [PyMySQL/mysqlclient-python#330]
I got this error when trying to pip install:

```
(venv) aaron@ ~/Documents/github/iam-data-services/backend_api/backend_api () $ pip install MySQL-Python
Collecting MySQL-Python
  Downloading https://files.pythonhosted.org/packages/a5/e9/51b544da85a36a68debe7a7091f068d802fc515a3a202652828c73453cad/MySQL-python-1.2.5.zip (108kB)
    100% |████████████████████████████████| 112kB 1.5MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/k5/bp3zwqms0bx9sp3p4mfl4vf80000gn/T/pip-install-ggeig3pl/MySQL-Python/setup.py", line 13, in <module>
        from setup_posix import get_config
      File "/private/var/folders/k5/bp3zwqms0bx9sp3p4mfl4vf80000gn/T/pip-install-ggeig3pl/MySQL-Python/setup_posix.py", line 2, in <module>
        from ConfigParser import SafeConfigParser
    ModuleNotFoundError: No module named 'ConfigParser'
```

I googled, and it looks related to Python3 support.

This is the SO Answer I found: 

[https://stackoverflow.com/a/14087705/1913888](https://stackoverflow.com/a/14087705/1913888)

Is there a way to pass this error and still use Python3?

**Comment by methane** [comment]
https://stackoverflow.com/a/23978968
