### ISSUE TITLE
mysqlclient already installed on macos, but still shows error when I was trying to run command python manage.py runserver

### ISSUE THREAD

**Issue by reddhu** [PyMySQL/mysqlclient-python#433]
here's what I saw when I run pip freeze

- Django==2.2.5
- mysql==0.0.2
- mysql-connector-python==8.0.20
- mysqlclient==1.4.6
- protobuf==3.12.2
- pytz==2020.1
- six==1.15.0
- sqlparse==0.3.1

and here's the error report when I run command python manage.py runserver

`Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/redd/.virtualenvs/Redd/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 15, in <module>
    import MySQLdb as Database
  File "/Users/redd/.virtualenvs/Redd/lib/python3.7/site-packages/MySQLdb/__init__.py", line 18, in <module>
    from . import _mysql
ImportError: dlopen(/Users/redd/.virtualenvs/Redd/lib/python3.7/site-packages/MySQLdb/_mysql.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libmysqlclient.21.dylib
  Referenced from: /Users/redd/.virtualenvs/Redd/lib/python3.7/site-packages/MySQLdb/_mysql.cpython-37m-darwin.so
  Reason: image not found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/redd/.virtualenvs/Redd/lib/python3.7/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/Users/redd/.virtualenvs/Redd/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/Users/redd/.virtualenvs/Redd/lib/python3.7/site-packages/django/utils/autoreload.py", line 77, in raise_last_exception
    raise _exception[1]
  File "/Users/redd/.virtualenvs/Redd/lib/python3.7/site-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/redd/.virtualenvs/Redd/lib/python3.7/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/Users/redd/.virtualenvs/Redd/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/redd/.virtualenvs/Redd/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/Users/redd/.virtualenvs/Redd/lib/python3.7/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/redd/.virtualenvs/Redd/lib/python3.7/site-packages/django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/Users/redd/.virtualenvs/Redd/lib/python3.7/site-packages/django/contrib/auth/base_user.py", line 47, in <module>
    class AbstractBaseUser(models.Model):
  File "/Users/redd/.virtualenvs/Redd/lib/python3.7/site-packages/django/db/models/base.py", line 117, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/Users/redd/.virtualenvs/Redd/lib/python3.7/site-packages/django/db/models/base.py", line 321, in add_to_class
    value.contribute_to_class(cls, name)
  File "/Users/redd/.virtualenvs/Redd/lib/python3.7/site-packages/django/db/models/options.py", line 204, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/Users/redd/.virtualenvs/Redd/lib/python3.7/site-packages/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/Users/redd/.virtualenvs/Redd/lib/python3.7/site-packages/django/db/utils.py", line 201, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/Users/redd/.virtualenvs/Redd/lib/python3.7/site-packages/django/db/utils.py", line 110, in load_backend
    return import_module('%s.base' % backend_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/redd/.virtualenvs/Redd/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 20, in <module>
    ) from err
django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module.
Did you install mysqlclient?`

**Comment by methane** [comment]
It is an issue of your environment.

**Comment by reddhu** [comment]
what can I do to solve this?



------------------&nbsp;Original message&nbsp;------------------
From: "Inada Naoki"; 
Sendtime: Monday, Jun 8, 2020 0:11 AM
To: "PyMySQL/mysqlclient-python"; 
Cc: "Redd"<745691279@qq.com>; "Author"; 
Subject: Re: [PyMySQL/mysqlclient-python] mysqlclient already installed on macos, but still shows error when I was trying to run command python manage.py runserver (#433)





 
It is an issue of your environment.

**Comment by methane** [comment]
learn how dynamic linker works

2020年6月8日(月) 1:24 reddhu <notifications@github.com>:

**Comment by reddhu** [comment]
Can you give me more details on how to use it to solve my issue? I already have mysqlclient installed and I am sure that I am using the correct python interpreter in virtual environment. I've had this issue for weeks and still can't find an available solution on this. Thank you so much for you time.

**Comment by dvdria2** [comment]
@reddhu have you solved this issue? I have the same problem.
