### ISSUE TITLE
NameError: name '_mysql' is not defined

### ISSUE THREAD

**Issue by sanjusci** [PyMySQL/mysqlclient-python#440]
Watching for file changes with StatReloader
Traceback (most recent call last):
  File "/Users/test.user/miniconda3/envs/news_network/lib/python3.7/site
  -packages
  /MySQLdb/__init__.py", line 18, in <module>
    from . import _mysql
ImportError: dlopen(/Users/test.user/miniconda3/envs/news_network/lib/python3.7
/site
-packages/MySQLdb/_mysql.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/mysql/lib/libmysqlclient.20.dylib
  Referenced from: /Users/test.user/miniconda3/envs/news_network/lib/python3.7
  /site
  -packages/MySQLdb/_mysql.cpython-37m-darwin.so
  Reason: image not found
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/test.user/miniconda3/envs/news_network/lib/python3.7/threading
  .py", 
  line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/test.user/miniconda3/envs/news_network/lib/python3.7/site
  -packages
  /django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/Users/test.user/miniconda3/envs/news_network/lib/python3.7/site
  -packages
  /django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/Users/test.user/miniconda3/envs/news_network/lib/python3.7/site
  -packages
  /django/utils/autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "/Users/test.user/miniconda3/envs/news_network/lib/python3.7/site
  -packages
  /django/core/management/__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/test.user/miniconda3/envs/news_network/lib/python3.7/site
  -packages
  /django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/Users/test.user/miniconda3/envs/news_network/lib/python3.7/site
  -packages
  /django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/test.user/miniconda3/envs/news_network/lib/python3.7/site
  -packages
  /django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/Users/test.user/miniconda3/envs/news_network/lib/python3.7/site
  -packages
  /django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/test.user/miniconda3/envs/news_network/lib/python3.7/importlib
  /__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/test.user/miniconda3/envs/news_network/lib/python3.7/site
  -packages
  /django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/Users/test.user/miniconda3/envs/news_network/lib/python3.7/site
  -packages
  /django/contrib/auth/base_user.py", line 47, in <module>
    class AbstractBaseUser(models.Model):
  File "/Users/test.user/miniconda3/envs/news_network/lib/python3.7/site
  -packages
  /django/db/models/base.py", line 121, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/Users/test.user/miniconda3/envs/news_network/lib/python3.7/site
  -packages
  /django/db/models/base.py", line 325, in add_to_class
    value.contribute_to_class(cls, name)
  File "/Users/test.user/miniconda3/envs/news_network/lib/python3.7/site
  -packages
  /django/db/models/options.py", line 208, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/Users/test.user/miniconda3/envs/news_network/lib/python3.7/site
  -packages
  /django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/Users/test.user/miniconda3/envs/news_network/lib/python3.7/site
  -packages
  /django/db/utils.py", line 207, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/Users/test.user/miniconda3/envs/news_network/lib/python3.7/site
  -packages
  /django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/Users/test.user/miniconda3/envs/news_network/lib/python3.7/importlib
  /__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/test.user/miniconda3/envs/news_network/lib/python3.7/site
  -packages
  /django/db/backends/mysql/base.py", line 16, in <module>
    import MySQLdb as Database
  File "/Users/test.user/miniconda3/envs/news_network/lib/python3.7/site
  -packages
  /MySQLdb/__init__.py", line 24, in <module>
    version_info, _mysql.version_info, _mysql.__file__

**Comment by methane** [comment]
**[You must not ask a support on issue tracker](https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde#.hdf6lpk11)**

Please ask to Python user community.

**Comment by nhondong** [comment]
Same error here. Any Solution?

**Comment by methane** [comment]
It's your environment issue and the package is built by conda, not me.
Don't ask support. OSS MAINTAINERS ARE NOT FREE TECH SUPPORT.
