### ISSUE TITLE
AssertionError when installing with pip

### ISSUE THREAD

**Issue by bendavis78** [PyMySQL/mysqlclient-python#65]
The package seems to install, but reports an AssertionError:

```
  ... snip ...
  running install_egg_info
  running egg_info
  writing dependency_links to mysqlclient.egg-info/dependency_links.txt
  writing top-level names to mysqlclient.egg-info/top_level.txt
  writing mysqlclient.egg-info/PKG-INFO
  warning: manifest_maker: standard file '-c' not found
  
  reading manifest file 'mysqlclient.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'mysqlclient.egg-info/SOURCES.txt'
  Copying mysqlclient.egg-info to build/bdist.linux-x86_64/wheel/mysqlclient-1.3.7-py3.5.egg-info
  running install_scripts
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-d3aeac06/mysqlclient/setup.py", line 21, in <module>
      setuptools.setup(**metadata)
    File "/usr/lib64/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib64/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib64/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/ben/Projects/gamestop-admin/env/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 213, in run
      archive_basename = self.get_archive_basename()
    File "/home/ben/Projects/gamestop-admin/env/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 161, in get_archive_basename
      impl_tag, abi_tag, plat_tag = self.get_tag()
    File "/home/ben/Projects/gamestop-admin/env/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 155, in get_tag
      assert tag == supported_tags[0]
  AssertionError
  
  ----------------------------------------
  Failed building wheel for mysqlclient
Failed to build mysqlclient
Installing collected packages: mysqlclient
  Running setup.py install for mysqlclient
Successfully installed mysqlclient-1.3.7
```

Full output here: http://sprunge.us/WYXf

**Comment by bendavis78** [comment]
Actually, this appears to happen with other packages too. Closing.
