### ISSUE TITLE
lib{ssl,crypto,z} images not found on MacOS X 10.11

### ISSUE THREAD

**Issue by awatts** [PyMySQL/mysqlclient-python#72]
I installed with ```pip install mysqlclient``` and tried the following command and got the following traceback:

```bash
(/hlpUsers/awatts/venvs/django_bcs)awatts@slate:~/venvs/django_bcs/CrowdExp$ ./manage.py inspectdb --database=sprrunner

Traceback (most recent call last):
  File "/hlpUsers/awatts/venvs/django_bcs/lib/python3.4/site-packages/django/db/backends/mysql/base.py", line 25, in <module>
    import MySQLdb as Database
  File "/hlpUsers/awatts/venvs/django_bcs/lib/python3.4/site-packages/MySQLdb/__init__.py", line 19, in <module>
    import _mysql
ImportError: dlopen(/hlpUsers/awatts/venvs/django_bcs/lib/python3.4/site-packages/_mysql.so, 2): Library not loaded: libssl.1.0.0.dylib
  Referenced from: /hlpUsers/awatts/venvs/django_bcs/lib/python3.4/site-packages/_mysql.so
  Reason: image not found
```

Checking the library dependencies:

````bash
(/hlpUsers/awatts/venvs/django_bcs)awatts@slate:~/venvs/django_bcs/CrowdExp$ otool -L /hlpUsers/awatts/venvs/django_bcs/lib/python3.4/site-packages/_mysql.so
/hlpUsers/awatts/venvs/django_bcs/lib/python3.4/site-packages/_mysql.so:
	/usr/local/opt/mariadb/lib/libmysqlclient.18.dylib (compatibility version 18.0.0, current version 18.0.0)
	libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 913.0.0)
```

And checking what versions of the libraries exist:

```bash
(/hlpUsers/awatts/venvs/django_bcs)awatts@slate:~/venvs/django_bcs/CrowdExp$ ls -l /usr/lib/libssl*
-rwxr-xr-x  1 root  wheel  404656 Dec  3 01:34 /usr/lib/libssl.0.9.7.dylib
-rwxr-xr-x  1 root  wheel  629056 Dec  3 01:34 /usr/lib/libssl.0.9.8.dylib
lrwxr-xr-x  1 root  wheel      18 Jan  6 16:11 /usr/lib/libssl.dylib -> libssl.0.9.8.dylib
(/hlpUsers/awatts/venvs/django_bcs)awatts@slate:~/venvs/django_bcs/CrowdExp$ ls -l /usr/lib/libcrypto*
-rwxr-xr-x  1 root  wheel  2114976 Dec  3 01:34 /usr/lib/libcrypto.0.9.7.dylib
-rwxr-xr-x  1 root  wheel  2682800 Dec  3 01:33 /usr/lib/libcrypto.0.9.8.dylib
lrwxr-xr-x  1 root  wheel       21 Jan  6 16:11 /usr/lib/libcrypto.dylib -> libcrypto.0.9.8.dylib
(/hlpUsers/awatts/venvs/django_bcs)awatts@slate:~/venvs/django_bcs/CrowdExp$ ls -l /usr/lib/libz*
lrwxr-xr-x  1 root  wheel      12 Jan  6 16:11 /usr/lib/libz.1.1.3.dylib -> libz.1.dylib
lrwxr-xr-x  1 root  wheel      12 Jan  6 16:11 /usr/lib/libz.1.2.5.dylib -> libz.1.dylib
-rwxr-xr-x  1 root  wheel  177392 Dec  3 01:34 /usr/lib/libz.1.dylib
lrwxr-xr-x  1 root  wheel      12 Jan  6 16:11 /usr/lib/libz.dylib -> libz.1.dylib
```

Due to SIP (System Integrity Protection) I can't even copy or link newer versions into ```/usr/lib/```

**Comment by methane** [comment]
I think you should fix your mysql_config.
mysqlclient-python uses it.

**Comment by awatts** [comment]
OK. Any suggestions as to how to fix it?

**Comment by awatts** [comment]
It looks like the problem is actually with Anaconda and pip. Closing, because I don't think there's anything mysqlclient can do to help.

**Comment by methane** [comment]
I suppose you can use `rpath` to link libmysqlclient correctly.
And you will be able to modify mysql_config to specify link options.

I'm not an expert of OS X and I haven't used OS X 10.11 yet.
Please google about how to set rpath.

**Comment by awatts** [comment]
Looks like that's what conda does. Further googling led me to the working solution of:

```bash
conda skeleton pypi mysqlclient
conda build mysqlclient
conda install /anaconda/conda-bld/osx-64/mysqlclient-1.3.7-py34_0.tar.bz2
```

And now:

```bash
(/hlpUsers/awatts/venvs/django_bcs)awatts@slate:~/venvs/django_bcs/CrowdExp$ otool -L /hlpUsers/awatts/venvs/django_bcs/lib/python3.4/site-packages/_mysql.so
/hlpUsers/awatts/venvs/django_bcs/lib/python3.4/site-packages/_mysql.so:
	/usr/local/opt/mariadb/lib/libmysqlclient.18.dylib (compatibility version 18.0.0, current version 18.0.0)
	@rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	@rpath/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```
